### ISSUE TITLE
[blog/post/typescript-prettier-eslint-next-js] Missing "plugin:react-hooks/recommended" in eslint config?

### ISSUE THREAD

**Issue by thomasmery** [paulintrognon/paulintrognon.fr#5]
Hi Paulin,

thanks a lot for the article :)

I was wondering if the _"plugin:react-hooks/recommended"_ was missing in the _eslint_ config

it seems I have to add it to get the desired reporting on bad hooks practices

Merci !

**Comment by thomasmery** [comment]
also this: https://github.com/vercel/next.js/tree/canary/examples/with-typescript-eslint-jest

has been added to the Next repo recently I think

**Comment by hyalen** [comment]
Hey Paulin, thanks for the article!!

It helped me a lot to configure the basics for my Next project with Typescript support =D

**Comment by paulintrognon** [comment]
> I was wondering if the _"plugin:react-hooks/recommended"_ was missing in the _eslint_ config

True! I have added it, thanks!

> also this: https://github.com/vercel/next.js/tree/canary/examples/with-typescript-eslint-jest has been added to the Next repo recently I think

Yes, that's right. My approach is a bit different though, I listed the main differences here: https://github.com/paulintrognon/next-typescript#what-is-the-difference-with-official-with-typescript-eslint-jest

Thank you for the feedback!

**Comment by paulintrognon** [comment]
Fixed in 412e7644b09cdbc65f567349c81f806304f8e771
